blank_issues_enabled: true
contact_links:
  - name: 💬 Обсуждения и Вопросы (GitHub Discussions)
    url: https://github.com/wqeww0001/TgwsProxyAndroid/discussions
    about: Задайте вопрос или обсудите работу приложения с сообществом.